import type { NextConfig } from 'next';
import { createMDX } from 'fumadocs-mdx/next';

const withMDX = createMDX();

const config: NextConfig = {
  // The .source/ directory is auto-generated by fumadocs-mdx and produces
  // complex inferred types that TypeScript cannot name. Runtime is safe.
  typescript: { ignoreBuildErrors: true },
};

export default withMDX(config);
