import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { REGISTRY, componentNames } from '../src/registry.js';

const _dir = dirname(fileURLToPath(import.meta.url));
const monoRoot = join(_dir, '..', '..', '..');
const cliRegistryRoot = join(_dir, '..', 'registry');
const coreSrc = join(monoRoot, 'packages', 'core', 'src');

async function main() {
  console.log('🔄 Syncing registry components...');
  await mkdir(cliRegistryRoot, { recursive: true });

  // 1. Generate _core.ts
  const themeTs = await readFile(join(coreSrc, 'theme.ts'), 'utf8');
  const tokensTs = await readFile(join(coreSrc, 'tokens.ts'), 'utf8');
  
  const coreContent = `// Auto-generated by sync-registry.ts
// Inlines @inkui-cli/core theme and tokens

${tokensTs}

${themeTs}
`;

  await writeFile(join(cliRegistryRoot, '_core.ts'), coreContent);
  console.log('✅ Generated _core.ts');

  // 2. Copy component files
  let copiedFiles = 0;
  for (const comp of componentNames) {
    const entry = REGISTRY[comp];
    if (!entry) continue;

    const srcDir = join(monoRoot, 'packages', comp, 'src');
    const destDir = join(cliRegistryRoot, comp);
    await mkdir(destDir, { recursive: true });

    for (const file of entry.files) {
      const srcPath = join(srcDir, file);
      const destPath = join(destDir, file);
      
      let content = await readFile(srcPath, 'utf8');
      
      // Rewrite core imports
      content = content.replace(/from\s+['"]@inkui-cli\/core['"]/g, "from '../_core.js'");
      
      await writeFile(destPath, content);
      copiedFiles++;
    }
  }

  console.log(`✨ Successfully synced ${copiedFiles} component files to apps/cli/registry/`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
